/***************************************************************************//**
 * @file
 * @brief This file contains definitions for storing ZCL attributes
 * in NVM tokens.
 *******************************************************************************
 * # License
 * <b>Copyright 2024 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/

// This file is generated by ZCL Advanced Platform generator. Please don't edit manually.

#include "af-types.h"
#include "sl_token_manager_defines.h"
#include "sl_token_manager_api.h"
#include "sl_zigbee_token.h"

#define NUM_PERSISTED_ZCL_ATTRIBUTES (10)


// Identifier tags for tokens
// Creator for attribute: on/off, endpoint: 1
#define CREATOR_ON_OFF_1 0xB000
#define NVM3KEY_ON_OFF_1 (NVM3KEY_DOMAIN_ZIGBEE | 0xB000)
#define COMMON_TOKEN_ON_OFF_1 SL_TOKEN_GET_DYNAMIC_TOKEN(NVM3KEY_ON_OFF_1, 0)
// Creator for attribute: start up on off, endpoint: 1
#define CREATOR_START_UP_ON_OFF_1 0xB001
#define NVM3KEY_START_UP_ON_OFF_1 (NVM3KEY_DOMAIN_ZIGBEE | 0xB001)
#define COMMON_TOKEN_START_UP_ON_OFF_1 SL_TOKEN_GET_DYNAMIC_TOKEN(NVM3KEY_START_UP_ON_OFF_1, 0)
// Creator for attribute: current level, endpoint: 1
#define CREATOR_CURRENT_LEVEL_1 0xB002
#define NVM3KEY_CURRENT_LEVEL_1 (NVM3KEY_DOMAIN_ZIGBEE | 0xB002)
#define COMMON_TOKEN_CURRENT_LEVEL_1 SL_TOKEN_GET_DYNAMIC_TOKEN(NVM3KEY_CURRENT_LEVEL_1, 0)
// Creator for attribute: start up current level, endpoint: 1
#define CREATOR_START_UP_CURRENT_LEVEL_1 0xB003
#define NVM3KEY_START_UP_CURRENT_LEVEL_1 (NVM3KEY_DOMAIN_ZIGBEE | 0xB003)
#define COMMON_TOKEN_START_UP_CURRENT_LEVEL_1 SL_TOKEN_GET_DYNAMIC_TOKEN(NVM3KEY_START_UP_CURRENT_LEVEL_1, 0)
// Creator for attribute: on/off, endpoint: 2
#define CREATOR_ON_OFF_2 0xB004
#define NVM3KEY_ON_OFF_2 (NVM3KEY_DOMAIN_ZIGBEE | 0xB004)
#define COMMON_TOKEN_ON_OFF_2 SL_TOKEN_GET_DYNAMIC_TOKEN(NVM3KEY_ON_OFF_2, 0)
// Creator for attribute: start up on off, endpoint: 2
#define CREATOR_START_UP_ON_OFF_2 0xB005
#define NVM3KEY_START_UP_ON_OFF_2 (NVM3KEY_DOMAIN_ZIGBEE | 0xB005)
#define COMMON_TOKEN_START_UP_ON_OFF_2 SL_TOKEN_GET_DYNAMIC_TOKEN(NVM3KEY_START_UP_ON_OFF_2, 0)
// Creator for attribute: current level, endpoint: 2
#define CREATOR_CURRENT_LEVEL_2 0xB006
#define NVM3KEY_CURRENT_LEVEL_2 (NVM3KEY_DOMAIN_ZIGBEE | 0xB006)
#define COMMON_TOKEN_CURRENT_LEVEL_2 SL_TOKEN_GET_DYNAMIC_TOKEN(NVM3KEY_CURRENT_LEVEL_2, 0)
// Creator for attribute: start up current level, endpoint: 2
#define CREATOR_START_UP_CURRENT_LEVEL_2 0xB007
#define NVM3KEY_START_UP_CURRENT_LEVEL_2 (NVM3KEY_DOMAIN_ZIGBEE | 0xB007)
#define COMMON_TOKEN_START_UP_CURRENT_LEVEL_2 SL_TOKEN_GET_DYNAMIC_TOKEN(NVM3KEY_START_UP_CURRENT_LEVEL_2, 0)
// Creator for attribute: color temperature, endpoint: 2
#define CREATOR_COLOR_CONTROL_COLOR_TEMPERATURE_2 0xB008
#define NVM3KEY_COLOR_CONTROL_COLOR_TEMPERATURE_2 (NVM3KEY_DOMAIN_ZIGBEE | 0xB008)
#define COMMON_TOKEN_COLOR_CONTROL_COLOR_TEMPERATURE_2 SL_TOKEN_GET_DYNAMIC_TOKEN(NVM3KEY_COLOR_CONTROL_COLOR_TEMPERATURE_2, 0)
// Creator for attribute: start up color temperature mireds, endpoint: 2
#define CREATOR_START_UP_COLOR_TEMPERATURE_MIREDS_2 0xB009
#define NVM3KEY_START_UP_COLOR_TEMPERATURE_MIREDS_2 (NVM3KEY_DOMAIN_ZIGBEE | 0xB009)
#define COMMON_TOKEN_START_UP_COLOR_TEMPERATURE_MIREDS_2 SL_TOKEN_GET_DYNAMIC_TOKEN(NVM3KEY_START_UP_COLOR_TEMPERATURE_MIREDS_2, 0)


// Types for the tokens
#ifdef DEFINETYPES
typedef uint8_t tokType_on_off;
        typedef uint8_t tokType_start_up_on_off;
        typedef uint8_t tokType_current_level;
        typedef uint8_t tokType_start_up_current_level;
        typedef uint16_t tokType_color_control_color_temperature;
        typedef uint16_t tokType_start_up_color_temperature_mireds;
        #endif // DEFINETYPES

// Actual token definitions
#ifdef DEFINETOKENS

DEFINE_BASIC_TOKEN(ON_OFF_1, tokType_on_off, 0x00)
DEFINE_BASIC_TOKEN(START_UP_ON_OFF_1, tokType_start_up_on_off, 0xFF)
DEFINE_BASIC_TOKEN(CURRENT_LEVEL_1, tokType_current_level, 0x00)
DEFINE_BASIC_TOKEN(START_UP_CURRENT_LEVEL_1, tokType_start_up_current_level, 0x33)
DEFINE_BASIC_TOKEN(ON_OFF_2, tokType_on_off, 0x00)
DEFINE_BASIC_TOKEN(START_UP_ON_OFF_2, tokType_start_up_on_off, 0xFF)
DEFINE_BASIC_TOKEN(CURRENT_LEVEL_2, tokType_current_level, 0x00)
DEFINE_BASIC_TOKEN(START_UP_CURRENT_LEVEL_2, tokType_start_up_current_level, 0x33)
DEFINE_BASIC_TOKEN(COLOR_CONTROL_COLOR_TEMPERATURE_2, tokType_color_control_color_temperature, 0x00FA)
DEFINE_BASIC_TOKEN(START_UP_COLOR_TEMPERATURE_MIREDS_2, tokType_start_up_color_temperature_mireds, 0x4444)
#endif // DEFINETOKENS

// Macro snippet that loads all the attributes from tokens
#define GENERATED_TOKEN_LOADER(endpoint) do { \
  uint8_t ptr[2]; \
  uint8_t curNetwork = sl_zigbee_get_current_network(); \
  uint8_t epNetwork; \
  epNetwork = sl_zigbee_af_network_index_from_endpoint(1); \
  if(1 == (endpoint) || (SL_ZIGBEE_BROADCAST_ENDPOINT == (endpoint) && epNetwork == curNetwork)) { \
    (void)slx_zigbee_token_manager_get_data(COMMON_TOKEN_CURRENT_LEVEL_1, (tokType_current_level *)ptr, sizeof(tokType_current_level)); \
    (void)sli_zigbee_af_write_attribute(1, ZCL_LEVEL_CONTROL_CLUSTER_ID, ZCL_CURRENT_LEVEL_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE, true, false, false); \
    (void)slx_zigbee_token_manager_get_data(COMMON_TOKEN_START_UP_CURRENT_LEVEL_1, (tokType_start_up_current_level *)ptr, sizeof(tokType_start_up_current_level)); \
    (void)sli_zigbee_af_write_attribute(1, ZCL_LEVEL_CONTROL_CLUSTER_ID, ZCL_START_UP_CURRENT_LEVEL_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE, true, false, false); \
    (void)slx_zigbee_token_manager_get_data(COMMON_TOKEN_ON_OFF_1, (tokType_on_off *)ptr, sizeof(tokType_on_off)); \
    (void)sli_zigbee_af_write_attribute(1, ZCL_ON_OFF_CLUSTER_ID, ZCL_ON_OFF_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_BOOLEAN_ATTRIBUTE_TYPE, true, false, false); \
    (void)slx_zigbee_token_manager_get_data(COMMON_TOKEN_START_UP_ON_OFF_1, (tokType_start_up_on_off *)ptr, sizeof(tokType_start_up_on_off)); \
    (void)sli_zigbee_af_write_attribute(1, ZCL_ON_OFF_CLUSTER_ID, ZCL_START_UP_ON_OFF_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_ENUM8_ATTRIBUTE_TYPE, true, false, false); \
  } \
  epNetwork = sl_zigbee_af_network_index_from_endpoint(2); \
  if(2 == (endpoint) || (SL_ZIGBEE_BROADCAST_ENDPOINT == (endpoint) && epNetwork == curNetwork)) { \
    (void)slx_zigbee_token_manager_get_data(COMMON_TOKEN_COLOR_CONTROL_COLOR_TEMPERATURE_2, (tokType_color_control_color_temperature *)ptr, sizeof(tokType_color_control_color_temperature)); \
    (void)sli_zigbee_af_write_attribute(2, ZCL_COLOR_CONTROL_CLUSTER_ID, ZCL_COLOR_CONTROL_COLOR_TEMPERATURE_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_INT16U_ATTRIBUTE_TYPE, true, false, false); \
    (void)slx_zigbee_token_manager_get_data(COMMON_TOKEN_START_UP_COLOR_TEMPERATURE_MIREDS_2, (tokType_start_up_color_temperature_mireds *)ptr, sizeof(tokType_start_up_color_temperature_mireds)); \
    (void)sli_zigbee_af_write_attribute(2, ZCL_COLOR_CONTROL_CLUSTER_ID, ZCL_START_UP_COLOR_TEMPERATURE_MIREDS_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_INT16U_ATTRIBUTE_TYPE, true, false, false); \
    (void)slx_zigbee_token_manager_get_data(COMMON_TOKEN_CURRENT_LEVEL_2, (tokType_current_level *)ptr, sizeof(tokType_current_level)); \
    (void)sli_zigbee_af_write_attribute(2, ZCL_LEVEL_CONTROL_CLUSTER_ID, ZCL_CURRENT_LEVEL_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE, true, false, false); \
    (void)slx_zigbee_token_manager_get_data(COMMON_TOKEN_START_UP_CURRENT_LEVEL_2, (tokType_start_up_current_level *)ptr, sizeof(tokType_start_up_current_level)); \
    (void)sli_zigbee_af_write_attribute(2, ZCL_LEVEL_CONTROL_CLUSTER_ID, ZCL_START_UP_CURRENT_LEVEL_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE, true, false, false); \
    (void)slx_zigbee_token_manager_get_data(COMMON_TOKEN_ON_OFF_2, (tokType_on_off *)ptr, sizeof(tokType_on_off)); \
    (void)sli_zigbee_af_write_attribute(2, ZCL_ON_OFF_CLUSTER_ID, ZCL_ON_OFF_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_BOOLEAN_ATTRIBUTE_TYPE, true, false, false); \
    (void)slx_zigbee_token_manager_get_data(COMMON_TOKEN_START_UP_ON_OFF_2, (tokType_start_up_on_off *)ptr, sizeof(tokType_start_up_on_off)); \
    (void)sli_zigbee_af_write_attribute(2, ZCL_ON_OFF_CLUSTER_ID, ZCL_START_UP_ON_OFF_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_ENUM8_ATTRIBUTE_TYPE, true, false, false); \
  } \
} while (false)

// Macro snippet that saves the attribute to token
#define GENERATED_TOKEN_SAVER do { \
  uint8_t allZeroData[2]; \
  memset(allZeroData, 0, 2);  \
  if ( data == NULL ) { data = allZeroData; } \
if ( 1 == endpoint ) { \
    if ( 0x0006 == clusterId ) { \
if ( 0x0000 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          (void)slx_zigbee_token_manager_set_data(COMMON_TOKEN_ON_OFF_1, data, sizeof(tokType_on_off)); \
if ( 0x4003 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          (void)slx_zigbee_token_manager_set_data(COMMON_TOKEN_START_UP_ON_OFF_1, data, sizeof(tokType_start_up_on_off)); \
    } \
    else if ( 0x0008 == clusterId ) { \
if ( 0x0000 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          (void)slx_zigbee_token_manager_set_data(COMMON_TOKEN_CURRENT_LEVEL_1, data, sizeof(tokType_current_level)); \
if ( 0x4000 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          (void)slx_zigbee_token_manager_set_data(COMMON_TOKEN_START_UP_CURRENT_LEVEL_1, data, sizeof(tokType_start_up_current_level)); \
    } \
} \
if ( 2 == endpoint ) { \
    if ( 0x0006 == clusterId ) { \
if ( 0x0000 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          (void)slx_zigbee_token_manager_set_data(COMMON_TOKEN_ON_OFF_2, data, sizeof(tokType_on_off)); \
if ( 0x4003 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          (void)slx_zigbee_token_manager_set_data(COMMON_TOKEN_START_UP_ON_OFF_2, data, sizeof(tokType_start_up_on_off)); \
    } \
    else if ( 0x0008 == clusterId ) { \
if ( 0x0000 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          (void)slx_zigbee_token_manager_set_data(COMMON_TOKEN_CURRENT_LEVEL_2, data, sizeof(tokType_current_level)); \
if ( 0x4000 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          (void)slx_zigbee_token_manager_set_data(COMMON_TOKEN_START_UP_CURRENT_LEVEL_2, data, sizeof(tokType_start_up_current_level)); \
    } \
    else if ( 0x0300 == clusterId ) { \
if ( 0x0007 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          (void)slx_zigbee_token_manager_set_data(COMMON_TOKEN_COLOR_CONTROL_COLOR_TEMPERATURE_2, data, sizeof(tokType_color_control_color_temperature)); \
if ( 0x4010 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          (void)slx_zigbee_token_manager_set_data(COMMON_TOKEN_START_UP_COLOR_TEMPERATURE_MIREDS_2, data, sizeof(tokType_start_up_color_temperature_mireds)); \
    } \
} \
} while (false)
